// Verilog font ROM table generated by Python
module font_rom (
    input [7:0] char_code,  // ASCII character code
    input [2:0] row,        // Row index (0 to 7)
    output reg [7:0] pixels // Pixel data for the selected row
);

    reg [7:0] font_memory [0:127][0:7];
    initial begin
        // Character:   (ASCII 32)
        font_memory[32][0] = 8'b00000000;
        font_memory[32][1] = 8'b00000000;
        font_memory[32][2] = 8'b00000000;
        font_memory[32][3] = 8'b00000000;
        font_memory[32][4] = 8'b00000000;
        font_memory[32][5] = 8'b00000000;
        font_memory[32][6] = 8'b00000000;
        font_memory[32][7] = 8'b00000000;

        // Character: ! (ASCII 33)
        font_memory[33][0] = 8'b00000100;
        font_memory[33][1] = 8'b00000100;
        font_memory[33][2] = 8'b00001000;
        font_memory[33][3] = 8'b00001000;
        font_memory[33][4] = 8'b00010000;
        font_memory[33][5] = 8'b00000000;
        font_memory[33][6] = 8'b00100000;
        font_memory[33][7] = 8'b00000000;

        // Character: " (ASCII 34)
        font_memory[34][0] = 8'b00100100;
        font_memory[34][1] = 8'b00100100;
        font_memory[34][2] = 8'b00000000;
        font_memory[34][3] = 8'b00000000;
        font_memory[34][4] = 8'b00000000;
        font_memory[34][5] = 8'b00000000;
        font_memory[34][6] = 8'b00000000;
        font_memory[34][7] = 8'b00000000;

        // Character: # (ASCII 35)
        font_memory[35][0] = 8'b00000000;
        font_memory[35][1] = 8'b00100100;
        font_memory[35][2] = 8'b01111110;
        font_memory[35][3] = 8'b00100100;
        font_memory[35][4] = 8'b00100100;
        font_memory[35][5] = 8'b01111110;
        font_memory[35][6] = 8'b00100100;
        font_memory[35][7] = 8'b00000000;

        // Character: $ (ASCII 36)
        font_memory[36][0] = 8'b00001000;
        font_memory[36][1] = 8'b00111100;
        font_memory[36][2] = 8'b01001000;
        font_memory[36][3] = 8'b00111100;
        font_memory[36][4] = 8'b00010010;
        font_memory[36][5] = 8'b01010010;
        font_memory[36][6] = 8'b00111100;
        font_memory[36][7] = 8'b00010000;

        // Character: % (ASCII 37)
        font_memory[37][0] = 8'b01000010;
        font_memory[37][1] = 8'b10100100;
        font_memory[37][2] = 8'b01001000;
        font_memory[37][3] = 8'b00010000;
        font_memory[37][4] = 8'b00100100;
        font_memory[37][5] = 8'b01001010;
        font_memory[37][6] = 8'b10000100;
        font_memory[37][7] = 8'b00000000;

        // Character: & (ASCII 38)
        font_memory[38][0] = 8'b00000000;
        font_memory[38][1] = 8'b00110000;
        font_memory[38][2] = 8'b01001000;
        font_memory[38][3] = 8'b00110010;
        font_memory[38][4] = 8'b01001100;
        font_memory[38][5] = 8'b01000100;
        font_memory[38][6] = 8'b00111010;
        font_memory[38][7] = 8'b00000000;

        // Character: ' (ASCII 39)
        font_memory[39][0] = 8'b00010000;
        font_memory[39][1] = 8'b00010000;
        font_memory[39][2] = 8'b00100000;
        font_memory[39][3] = 8'b00000000;
        font_memory[39][4] = 8'b00000000;
        font_memory[39][5] = 8'b00000000;
        font_memory[39][6] = 8'b00000000;
        font_memory[39][7] = 8'b00000000;

        // Character: ( (ASCII 40)
        font_memory[40][0] = 8'b00000100;
        font_memory[40][1] = 8'b00001000;
        font_memory[40][2] = 8'b00010000;
        font_memory[40][3] = 8'b00010000;
        font_memory[40][4] = 8'b00010000;
        font_memory[40][5] = 8'b00010000;
        font_memory[40][6] = 8'b00001000;
        font_memory[40][7] = 8'b00000100;

        // Character: ) (ASCII 41)
        font_memory[41][0] = 8'b00100000;
        font_memory[41][1] = 8'b00010000;
        font_memory[41][2] = 8'b00001000;
        font_memory[41][3] = 8'b00001000;
        font_memory[41][4] = 8'b00001000;
        font_memory[41][5] = 8'b00001000;
        font_memory[41][6] = 8'b00010000;
        font_memory[41][7] = 8'b00100000;

        // Character: * (ASCII 42)
        font_memory[42][0] = 8'b00010000;
        font_memory[42][1] = 8'b01010100;
        font_memory[42][2] = 8'b00111000;
        font_memory[42][3] = 8'b01010100;
        font_memory[42][4] = 8'b00010000;
        font_memory[42][5] = 8'b00000000;
        font_memory[42][6] = 8'b00000000;
        font_memory[42][7] = 8'b00000000;

        // Character: + (ASCII 43)
        font_memory[43][0] = 8'b00000000;
        font_memory[43][1] = 8'b00010000;
        font_memory[43][2] = 8'b00010000;
        font_memory[43][3] = 8'b01111100;
        font_memory[43][4] = 8'b00010000;
        font_memory[43][5] = 8'b00010000;
        font_memory[43][6] = 8'b00000000;
        font_memory[43][7] = 8'b00000000;

        // Character: , (ASCII 44)
        font_memory[44][0] = 8'b00000000;
        font_memory[44][1] = 8'b00000000;
        font_memory[44][2] = 8'b00000000;
        font_memory[44][3] = 8'b00000000;
        font_memory[44][4] = 8'b00000000;
        font_memory[44][5] = 8'b00000000;
        font_memory[44][6] = 8'b00010000;
        font_memory[44][7] = 8'b00100000;

        // Character: - (ASCII 45)
        font_memory[45][0] = 8'b00000000;
        font_memory[45][1] = 8'b00000000;
        font_memory[45][2] = 8'b00000000;
        font_memory[45][3] = 8'b01111100;
        font_memory[45][4] = 8'b00000000;
        font_memory[45][5] = 8'b00000000;
        font_memory[45][6] = 8'b00000000;
        font_memory[45][7] = 8'b00000000;

        // Character: . (ASCII 46)
        font_memory[46][0] = 8'b00000000;
        font_memory[46][1] = 8'b00000000;
        font_memory[46][2] = 8'b00000000;
        font_memory[46][3] = 8'b00000000;
        font_memory[46][4] = 8'b00000000;
        font_memory[46][5] = 8'b00000000;
        font_memory[46][6] = 8'b00010000;
        font_memory[46][7] = 8'b00000000;

        // Character: / (ASCII 47)
        font_memory[47][0] = 8'b00000100;
        font_memory[47][1] = 8'b00001000;
        font_memory[47][2] = 8'b00001000;
        font_memory[47][3] = 8'b00010000;
        font_memory[47][4] = 8'b00100000;
        font_memory[47][5] = 8'b00100000;
        font_memory[47][6] = 8'b01000000;
        font_memory[47][7] = 8'b00000000;

        // Character: 0 (ASCII 48)
        font_memory[48][0] = 8'b00011100;
        font_memory[48][1] = 8'b00100010;
        font_memory[48][2] = 8'b01000010;
        font_memory[48][3] = 8'b01000010;
        font_memory[48][4] = 8'b01000010;
        font_memory[48][5] = 8'b01000100;
        font_memory[48][6] = 8'b00111000;
        font_memory[48][7] = 8'b00000000;

        // Character: 1 (ASCII 49)
        font_memory[49][0] = 8'b00010000;
        font_memory[49][1] = 8'b00110000;
        font_memory[49][2] = 8'b00010000;
        font_memory[49][3] = 8'b00010000;
        font_memory[49][4] = 8'b00010000;
        font_memory[49][5] = 8'b00010000;
        font_memory[49][6] = 8'b01111100;
        font_memory[49][7] = 8'b00000000;

        // Character: 2 (ASCII 50)
        font_memory[50][0] = 8'b00111100;
        font_memory[50][1] = 8'b01000010;
        font_memory[50][2] = 8'b00000010;
        font_memory[50][3] = 8'b00001100;
        font_memory[50][4] = 8'b00110000;
        font_memory[50][5] = 8'b01000000;
        font_memory[50][6] = 8'b01111110;
        font_memory[50][7] = 8'b00000000;

        // Character: 3 (ASCII 51)
        font_memory[51][0] = 8'b00111110;
        font_memory[51][1] = 8'b00000100;
        font_memory[51][2] = 8'b00001000;
        font_memory[51][3] = 8'b00011100;
        font_memory[51][4] = 8'b00000010;
        font_memory[51][5] = 8'b01000010;
        font_memory[51][6] = 8'b00111100;
        font_memory[51][7] = 8'b00000000;

        // Character: 4 (ASCII 52)
        font_memory[52][0] = 8'b00001100;
        font_memory[52][1] = 8'b00010100;
        font_memory[52][2] = 8'b00100100;
        font_memory[52][3] = 8'b01000100;
        font_memory[52][4] = 8'b01111110;
        font_memory[52][5] = 8'b00000100;
        font_memory[52][6] = 8'b00000100;
        font_memory[52][7] = 8'b00000000;

        // Character: 5 (ASCII 53)
        font_memory[53][0] = 8'b00111110;
        font_memory[53][1] = 8'b00100000;
        font_memory[53][2] = 8'b00111100;
        font_memory[53][3] = 8'b00000010;
        font_memory[53][4] = 8'b00000010;
        font_memory[53][5] = 8'b01000010;
        font_memory[53][6] = 8'b00111100;
        font_memory[53][7] = 8'b00000000;

        // Character: 6 (ASCII 54)
        font_memory[54][0] = 8'b00011100;
        font_memory[54][1] = 8'b00100000;
        font_memory[54][2] = 8'b01000000;
        font_memory[54][3] = 8'b01111100;
        font_memory[54][4] = 8'b01000010;
        font_memory[54][5] = 8'b01000010;
        font_memory[54][6] = 8'b00111100;
        font_memory[54][7] = 8'b00000000;

        // Character: 7 (ASCII 55)
        font_memory[55][0] = 8'b01111110;
        font_memory[55][1] = 8'b01000010;
        font_memory[55][2] = 8'b00000100;
        font_memory[55][3] = 8'b00001000;
        font_memory[55][4] = 8'b00001000;
        font_memory[55][5] = 8'b00010000;
        font_memory[55][6] = 8'b00010000;
        font_memory[55][7] = 8'b00000000;

        // Character: 8 (ASCII 56)
        font_memory[56][0] = 8'b00111000;
        font_memory[56][1] = 8'b01000100;
        font_memory[56][2] = 8'b01000100;
        font_memory[56][3] = 8'b00111100;
        font_memory[56][4] = 8'b01000010;
        font_memory[56][5] = 8'b01000010;
        font_memory[56][6] = 8'b00111100;
        font_memory[56][7] = 8'b00000000;

        // Character: 9 (ASCII 57)
        font_memory[57][0] = 8'b00111100;
        font_memory[57][1] = 8'b01000010;
        font_memory[57][2] = 8'b01000010;
        font_memory[57][3] = 8'b00111110;
        font_memory[57][4] = 8'b00000010;
        font_memory[57][5] = 8'b00000100;
        font_memory[57][6] = 8'b00111000;
        font_memory[57][7] = 8'b00000000;

        // Character: : (ASCII 58)
        font_memory[58][0] = 8'b00000000;
        font_memory[58][1] = 8'b00010000;
        font_memory[58][2] = 8'b00000000;
        font_memory[58][3] = 8'b00000000;
        font_memory[58][4] = 8'b00000000;
        font_memory[58][5] = 8'b00000000;
        font_memory[58][6] = 8'b00010000;
        font_memory[58][7] = 8'b00000000;

        // Character: ; (ASCII 59)
        font_memory[59][0] = 8'b00000000;
        font_memory[59][1] = 8'b00010000;
        font_memory[59][2] = 8'b00000000;
        font_memory[59][3] = 8'b00000000;
        font_memory[59][4] = 8'b00000000;
        font_memory[59][5] = 8'b00000000;
        font_memory[59][6] = 8'b00010000;
        font_memory[59][7] = 8'b00100000;

        // Character: < (ASCII 60)
        font_memory[60][0] = 8'b00000000;
        font_memory[60][1] = 8'b00000110;
        font_memory[60][2] = 8'b00011000;
        font_memory[60][3] = 8'b00100000;
        font_memory[60][4] = 8'b00011000;
        font_memory[60][5] = 8'b00000110;
        font_memory[60][6] = 8'b00000000;
        font_memory[60][7] = 8'b00000000;

        // Character: = (ASCII 61)
        font_memory[61][0] = 8'b00000000;
        font_memory[61][1] = 8'b00000000;
        font_memory[61][2] = 8'b00111110;
        font_memory[61][3] = 8'b00000000;
        font_memory[61][4] = 8'b00111110;
        font_memory[61][5] = 8'b00000000;
        font_memory[61][6] = 8'b00000000;
        font_memory[61][7] = 8'b00000000;

        // Character: > (ASCII 62)
        font_memory[62][0] = 8'b00000000;
        font_memory[62][1] = 8'b00110000;
        font_memory[62][2] = 8'b00001100;
        font_memory[62][3] = 8'b00000010;
        font_memory[62][4] = 8'b00001100;
        font_memory[62][5] = 8'b00110000;
        font_memory[62][6] = 8'b00000000;
        font_memory[62][7] = 8'b00000000;

        // Character: ? (ASCII 63)
        font_memory[63][0] = 8'b00111100;
        font_memory[63][1] = 8'b01000010;
        font_memory[63][2] = 8'b00000010;
        font_memory[63][3] = 8'b00001100;
        font_memory[63][4] = 8'b00010000;
        font_memory[63][5] = 8'b00000000;
        font_memory[63][6] = 8'b00010000;
        font_memory[63][7] = 8'b00000000;

        // Character: @ (ASCII 64)
        font_memory[64][0] = 8'b00111100;
        font_memory[64][1] = 8'b01000010;
        font_memory[64][2] = 8'b10011010;
        font_memory[64][3] = 8'b10101010;
        font_memory[64][4] = 8'b10111100;
        font_memory[64][5] = 8'b10000000;
        font_memory[64][6] = 8'b01111100;
        font_memory[64][7] = 8'b00000000;

        // Character: A (ASCII 65)
        font_memory[65][0] = 8'b00011000;
        font_memory[65][1] = 8'b00100100;
        font_memory[65][2] = 8'b00100100;
        font_memory[65][3] = 8'b01000010;
        font_memory[65][4] = 8'b01111110;
        font_memory[65][5] = 8'b01000010;
        font_memory[65][6] = 8'b01000010;
        font_memory[65][7] = 8'b00000000;

        // Character: B (ASCII 66)
        font_memory[66][0] = 8'b01111000;
        font_memory[66][1] = 8'b01000100;
        font_memory[66][2] = 8'b01000100;
        font_memory[66][3] = 8'b01111100;
        font_memory[66][4] = 8'b01000010;
        font_memory[66][5] = 8'b01000010;
        font_memory[66][6] = 8'b01111100;
        font_memory[66][7] = 8'b00000000;

        // Character: C (ASCII 67)
        font_memory[67][0] = 8'b00011100;
        font_memory[67][1] = 8'b00100010;
        font_memory[67][2] = 8'b01000000;
        font_memory[67][3] = 8'b01000000;
        font_memory[67][4] = 8'b01000000;
        font_memory[67][5] = 8'b00100010;
        font_memory[67][6] = 8'b00011100;
        font_memory[67][7] = 8'b00000000;

        // Character: D (ASCII 68)
        font_memory[68][0] = 8'b01111000;
        font_memory[68][1] = 8'b01000100;
        font_memory[68][2] = 8'b01000010;
        font_memory[68][3] = 8'b01000010;
        font_memory[68][4] = 8'b01000010;
        font_memory[68][5] = 8'b01000100;
        font_memory[68][6] = 8'b01111000;
        font_memory[68][7] = 8'b00000000;

        // Character: E (ASCII 69)
        font_memory[69][0] = 8'b01111110;
        font_memory[69][1] = 8'b01000000;
        font_memory[69][2] = 8'b01000000;
        font_memory[69][3] = 8'b01111000;
        font_memory[69][4] = 8'b01000000;
        font_memory[69][5] = 8'b01000000;
        font_memory[69][6] = 8'b01111110;
        font_memory[69][7] = 8'b00000000;

        // Character: F (ASCII 70)
        font_memory[70][0] = 8'b01111110;
        font_memory[70][1] = 8'b01000000;
        font_memory[70][2] = 8'b01000000;
        font_memory[70][3] = 8'b01111000;
        font_memory[70][4] = 8'b01000000;
        font_memory[70][5] = 8'b01000000;
        font_memory[70][6] = 8'b01000000;
        font_memory[70][7] = 8'b00000000;

        // Character: G (ASCII 71)
        font_memory[71][0] = 8'b00011110;
        font_memory[71][1] = 8'b00100000;
        font_memory[71][2] = 8'b01000000;
        font_memory[71][3] = 8'b01000110;
        font_memory[71][4] = 8'b01000010;
        font_memory[71][5] = 8'b00100010;
        font_memory[71][6] = 8'b00011110;
        font_memory[71][7] = 8'b00000000;

        // Character: H (ASCII 72)
        font_memory[72][0] = 8'b01000010;
        font_memory[72][1] = 8'b01000010;
        font_memory[72][2] = 8'b01000010;
        font_memory[72][3] = 8'b01111110;
        font_memory[72][4] = 8'b01000010;
        font_memory[72][5] = 8'b01000010;
        font_memory[72][6] = 8'b01000010;
        font_memory[72][7] = 8'b00000000;

        // Character: I (ASCII 73)
        font_memory[73][0] = 8'b01111100;
        font_memory[73][1] = 8'b00010000;
        font_memory[73][2] = 8'b00010000;
        font_memory[73][3] = 8'b00010000;
        font_memory[73][4] = 8'b00010000;
        font_memory[73][5] = 8'b00010000;
        font_memory[73][6] = 8'b01111100;
        font_memory[73][7] = 8'b00000000;

        // Character: J (ASCII 74)
        font_memory[74][0] = 8'b00011110;
        font_memory[74][1] = 8'b00000010;
        font_memory[74][2] = 8'b00000010;
        font_memory[74][3] = 8'b00000010;
        font_memory[74][4] = 8'b01000010;
        font_memory[74][5] = 8'b01000100;
        font_memory[74][6] = 8'b00111000;
        font_memory[74][7] = 8'b00000000;

        // Character: K (ASCII 75)
        font_memory[75][0] = 8'b01000100;
        font_memory[75][1] = 8'b01001000;
        font_memory[75][2] = 8'b01010000;
        font_memory[75][3] = 8'b01111000;
        font_memory[75][4] = 8'b01000100;
        font_memory[75][5] = 8'b01000100;
        font_memory[75][6] = 8'b01000010;
        font_memory[75][7] = 8'b00000000;

        // Character: L (ASCII 76)
        font_memory[76][0] = 8'b01000000;
        font_memory[76][1] = 8'b01000000;
        font_memory[76][2] = 8'b01000000;
        font_memory[76][3] = 8'b01000000;
        font_memory[76][4] = 8'b01000000;
        font_memory[76][5] = 8'b01000000;
        font_memory[76][6] = 8'b01111110;
        font_memory[76][7] = 8'b00000000;

        // Character: M (ASCII 77)
        font_memory[77][0] = 8'b10000010;
        font_memory[77][1] = 8'b11000110;
        font_memory[77][2] = 8'b11000110;
        font_memory[77][3] = 8'b10101010;
        font_memory[77][4] = 8'b10101010;
        font_memory[77][5] = 8'b10010010;
        font_memory[77][6] = 8'b10010010;
        font_memory[77][7] = 8'b00000000;

        // Character: N (ASCII 78)
        font_memory[78][0] = 8'b01100010;
        font_memory[78][1] = 8'b01100010;
        font_memory[78][2] = 8'b01010010;
        font_memory[78][3] = 8'b01010010;
        font_memory[78][4] = 8'b01001010;
        font_memory[78][5] = 8'b01001010;
        font_memory[78][6] = 8'b01000110;
        font_memory[78][7] = 8'b00000000;

        // Character: O (ASCII 79)
        font_memory[79][0] = 8'b00011100;
        font_memory[79][1] = 8'b00100010;
        font_memory[79][2] = 8'b01000010;
        font_memory[79][3] = 8'b01000010;
        font_memory[79][4] = 8'b01000010;
        font_memory[79][5] = 8'b01000100;
        font_memory[79][6] = 8'b00111000;
        font_memory[79][7] = 8'b00000000;

        // Character: P (ASCII 80)
        font_memory[80][0] = 8'b01111100;
        font_memory[80][1] = 8'b01000010;
        font_memory[80][2] = 8'b01000010;
        font_memory[80][3] = 8'b01000100;
        font_memory[80][4] = 8'b01111000;
        font_memory[80][5] = 8'b01000000;
        font_memory[80][6] = 8'b01000000;
        font_memory[80][7] = 8'b00000000;

        // Character: Q (ASCII 81)
        font_memory[81][0] = 8'b00011100;
        font_memory[81][1] = 8'b00100010;
        font_memory[81][2] = 8'b01000010;
        font_memory[81][3] = 8'b01000010;
        font_memory[81][4] = 8'b01000010;
        font_memory[81][5] = 8'b01010100;
        font_memory[81][6] = 8'b00111000;
        font_memory[81][7] = 8'b00000100;

        // Character: R (ASCII 82)
        font_memory[82][0] = 8'b01111100;
        font_memory[82][1] = 8'b01000010;
        font_memory[82][2] = 8'b01000010;
        font_memory[82][3] = 8'b01000100;
        font_memory[82][4] = 8'b01111100;
        font_memory[82][5] = 8'b01000100;
        font_memory[82][6] = 8'b01000010;
        font_memory[82][7] = 8'b00000000;

        // Character: S (ASCII 83)
        font_memory[83][0] = 8'b00111000;
        font_memory[83][1] = 8'b01000100;
        font_memory[83][2] = 8'b01000000;
        font_memory[83][3] = 8'b00111100;
        font_memory[83][4] = 8'b00000010;
        font_memory[83][5] = 8'b01000010;
        font_memory[83][6] = 8'b00111100;
        font_memory[83][7] = 8'b00000000;

        // Character: T (ASCII 84)
        font_memory[84][0] = 8'b11111110;
        font_memory[84][1] = 8'b00010000;
        font_memory[84][2] = 8'b00010000;
        font_memory[84][3] = 8'b00010000;
        font_memory[84][4] = 8'b00010000;
        font_memory[84][5] = 8'b00010000;
        font_memory[84][6] = 8'b00010000;
        font_memory[84][7] = 8'b00000000;

        // Character: U (ASCII 85)
        font_memory[85][0] = 8'b01000010;
        font_memory[85][1] = 8'b01000010;
        font_memory[85][2] = 8'b01000010;
        font_memory[85][3] = 8'b01000010;
        font_memory[85][4] = 8'b01000010;
        font_memory[85][5] = 8'b01000100;
        font_memory[85][6] = 8'b00111000;
        font_memory[85][7] = 8'b00000000;

        // Character: V (ASCII 86)
        font_memory[86][0] = 8'b01000010;
        font_memory[86][1] = 8'b01000010;
        font_memory[86][2] = 8'b01000010;
        font_memory[86][3] = 8'b00100100;
        font_memory[86][4] = 8'b00100100;
        font_memory[86][5] = 8'b00011000;
        font_memory[86][6] = 8'b00011000;
        font_memory[86][7] = 8'b00000000;

        // Character: W (ASCII 87)
        font_memory[87][0] = 8'b10010010;
        font_memory[87][1] = 8'b10010010;
        font_memory[87][2] = 8'b10010010;
        font_memory[87][3] = 8'b01010100;
        font_memory[87][4] = 8'b01101100;
        font_memory[87][5] = 8'b00101000;
        font_memory[87][6] = 8'b00101000;
        font_memory[87][7] = 8'b00000000;

        // Character: X (ASCII 88)
        font_memory[88][0] = 8'b01000010;
        font_memory[88][1] = 8'b01000010;
        font_memory[88][2] = 8'b00100100;
        font_memory[88][3] = 8'b00011000;
        font_memory[88][4] = 8'b00100100;
        font_memory[88][5] = 8'b01000010;
        font_memory[88][6] = 8'b01000010;
        font_memory[88][7] = 8'b00000000;

        // Character: Y (ASCII 89)
        font_memory[89][0] = 8'b01000100;
        font_memory[89][1] = 8'b01000100;
        font_memory[89][2] = 8'b00101000;
        font_memory[89][3] = 8'b00010000;
        font_memory[89][4] = 8'b00010000;
        font_memory[89][5] = 8'b00010000;
        font_memory[89][6] = 8'b00010000;
        font_memory[89][7] = 8'b00000000;

        // Character: Z (ASCII 90)
        font_memory[90][0] = 8'b01111110;
        font_memory[90][1] = 8'b00000100;
        font_memory[90][2] = 8'b00001000;
        font_memory[90][3] = 8'b00010000;
        font_memory[90][4] = 8'b00100000;
        font_memory[90][5] = 8'b01000000;
        font_memory[90][6] = 8'b01111110;
        font_memory[90][7] = 8'b00000000;

        // Character: [ (ASCII 91)
        font_memory[91][0] = 8'b00011100;
        font_memory[91][1] = 8'b00010000;
        font_memory[91][2] = 8'b00010000;
        font_memory[91][3] = 8'b00010000;
        font_memory[91][4] = 8'b00010000;
        font_memory[91][5] = 8'b00010000;
        font_memory[91][6] = 8'b00010000;
        font_memory[91][7] = 8'b00011100;

        // Character: \ (ASCII 92)
        font_memory[92][0] = 8'b01000000;
        font_memory[92][1] = 8'b00100000;
        font_memory[92][2] = 8'b00100000;
        font_memory[92][3] = 8'b00010000;
        font_memory[92][4] = 8'b00001000;
        font_memory[92][5] = 8'b00001000;
        font_memory[92][6] = 8'b00000100;
        font_memory[92][7] = 8'b00000000;

        // Character: ] (ASCII 93)
        font_memory[93][0] = 8'b00111000;
        font_memory[93][1] = 8'b00001000;
        font_memory[93][2] = 8'b00001000;
        font_memory[93][3] = 8'b00001000;
        font_memory[93][4] = 8'b00001000;
        font_memory[93][5] = 8'b00001000;
        font_memory[93][6] = 8'b00001000;
        font_memory[93][7] = 8'b00111000;

        // Character: ^ (ASCII 94)
        font_memory[94][0] = 8'b00010000;
        font_memory[94][1] = 8'b00101000;
        font_memory[94][2] = 8'b01000100;
        font_memory[94][3] = 8'b00000000;
        font_memory[94][4] = 8'b00000000;
        font_memory[94][5] = 8'b00000000;
        font_memory[94][6] = 8'b00000000;
        font_memory[94][7] = 8'b00000000;

        // Character: _ (ASCII 95)
        font_memory[95][0] = 8'b00000000;
        font_memory[95][1] = 8'b00000000;
        font_memory[95][2] = 8'b00000000;
        font_memory[95][3] = 8'b00000000;
        font_memory[95][4] = 8'b00000000;
        font_memory[95][5] = 8'b00000000;
        font_memory[95][6] = 8'b00000000;
        font_memory[95][7] = 8'b01111110;

        // Character: ` (ASCII 96)
        font_memory[96][0] = 8'b00100000;
        font_memory[96][1] = 8'b00010000;
        font_memory[96][2] = 8'b00000000;
        font_memory[96][3] = 8'b00000000;
        font_memory[96][4] = 8'b00000000;
        font_memory[96][5] = 8'b00000000;
        font_memory[96][6] = 8'b00000000;
        font_memory[96][7] = 8'b00000000;

        // Character: a (ASCII 97)
        font_memory[97][0] = 8'b00000000;
        font_memory[97][1] = 8'b00000000;
        font_memory[97][2] = 8'b00111100;
        font_memory[97][3] = 8'b00000010;
        font_memory[97][4] = 8'b00111110;
        font_memory[97][5] = 8'b01000010;
        font_memory[97][6] = 8'b00111110;
        font_memory[97][7] = 8'b00000000;

        // Character: b (ASCII 98)
        font_memory[98][0] = 8'b01000000;
        font_memory[98][1] = 8'b01000000;
        font_memory[98][2] = 8'b01011100;
        font_memory[98][3] = 8'b01100010;
        font_memory[98][4] = 8'b01000010;
        font_memory[98][5] = 8'b01000010;
        font_memory[98][6] = 8'b01111100;
        font_memory[98][7] = 8'b00000000;

        // Character: c (ASCII 99)
        font_memory[99][0] = 8'b00000000;
        font_memory[99][1] = 8'b00000000;
        font_memory[99][2] = 8'b00011100;
        font_memory[99][3] = 8'b00100010;
        font_memory[99][4] = 8'b01000000;
        font_memory[99][5] = 8'b01000000;
        font_memory[99][6] = 8'b00111100;
        font_memory[99][7] = 8'b00000000;

        // Character: d (ASCII 100)
        font_memory[100][0] = 8'b00000010;
        font_memory[100][1] = 8'b00000010;
        font_memory[100][2] = 8'b00111110;
        font_memory[100][3] = 8'b01000010;
        font_memory[100][4] = 8'b01000010;
        font_memory[100][5] = 8'b01000110;
        font_memory[100][6] = 8'b00111010;
        font_memory[100][7] = 8'b00000000;

        // Character: e (ASCII 101)
        font_memory[101][0] = 8'b00000000;
        font_memory[101][1] = 8'b00000000;
        font_memory[101][2] = 8'b00111100;
        font_memory[101][3] = 8'b01000010;
        font_memory[101][4] = 8'b01111110;
        font_memory[101][5] = 8'b01000000;
        font_memory[101][6] = 8'b00111100;
        font_memory[101][7] = 8'b00000000;

        // Character: f (ASCII 102)
        font_memory[102][0] = 8'b00001100;
        font_memory[102][1] = 8'b00010000;
        font_memory[102][2] = 8'b00111100;
        font_memory[102][3] = 8'b00010000;
        font_memory[102][4] = 8'b00010000;
        font_memory[102][5] = 8'b00010000;
        font_memory[102][6] = 8'b00010000;
        font_memory[102][7] = 8'b00000000;

        // Character: g (ASCII 103)
        font_memory[103][0] = 8'b00000000;
        font_memory[103][1] = 8'b00000000;
        font_memory[103][2] = 8'b00111010;
        font_memory[103][3] = 8'b01000100;
        font_memory[103][4] = 8'b00111000;
        font_memory[103][5] = 8'b00001100;
        font_memory[103][6] = 8'b01000010;
        font_memory[103][7] = 8'b00111100;

        // Character: h (ASCII 104)
        font_memory[104][0] = 8'b01000000;
        font_memory[104][1] = 8'b01000000;
        font_memory[104][2] = 8'b01011100;
        font_memory[104][3] = 8'b01100010;
        font_memory[104][4] = 8'b01000010;
        font_memory[104][5] = 8'b01000010;
        font_memory[104][6] = 8'b01000010;
        font_memory[104][7] = 8'b00000000;

        // Character: i (ASCII 105)
        font_memory[105][0] = 8'b00010000;
        font_memory[105][1] = 8'b00000000;
        font_memory[105][2] = 8'b00010000;
        font_memory[105][3] = 8'b00010000;
        font_memory[105][4] = 8'b00010000;
        font_memory[105][5] = 8'b00010000;
        font_memory[105][6] = 8'b00010000;
        font_memory[105][7] = 8'b00000000;

        // Character: j (ASCII 106)
        font_memory[106][0] = 8'b00001000;
        font_memory[106][1] = 8'b00000000;
        font_memory[106][2] = 8'b00001000;
        font_memory[106][3] = 8'b00001000;
        font_memory[106][4] = 8'b00001000;
        font_memory[106][5] = 8'b00001000;
        font_memory[106][6] = 8'b00010000;
        font_memory[106][7] = 8'b01100000;

        // Character: k (ASCII 107)
        font_memory[107][0] = 8'b01000000;
        font_memory[107][1] = 8'b01000000;
        font_memory[107][2] = 8'b01001000;
        font_memory[107][3] = 8'b01010000;
        font_memory[107][4] = 8'b01110000;
        font_memory[107][5] = 8'b01001000;
        font_memory[107][6] = 8'b01000110;
        font_memory[107][7] = 8'b00000000;

        // Character: l (ASCII 108)
        font_memory[108][0] = 8'b00010000;
        font_memory[108][1] = 8'b00010000;
        font_memory[108][2] = 8'b00010000;
        font_memory[108][3] = 8'b00010000;
        font_memory[108][4] = 8'b00010000;
        font_memory[108][5] = 8'b00010000;
        font_memory[108][6] = 8'b00010000;
        font_memory[108][7] = 8'b00000000;

        // Character: m (ASCII 109)
        font_memory[109][0] = 8'b00000000;
        font_memory[109][1] = 8'b00000000;
        font_memory[109][2] = 8'b10100100;
        font_memory[109][3] = 8'b11011010;
        font_memory[109][4] = 8'b10010010;
        font_memory[109][5] = 8'b10010010;
        font_memory[109][6] = 8'b10010010;
        font_memory[109][7] = 8'b00000000;

        // Character: n (ASCII 110)
        font_memory[110][0] = 8'b00000000;
        font_memory[110][1] = 8'b00000000;
        font_memory[110][2] = 8'b01011100;
        font_memory[110][3] = 8'b01100010;
        font_memory[110][4] = 8'b01000010;
        font_memory[110][5] = 8'b01000010;
        font_memory[110][6] = 8'b01000010;
        font_memory[110][7] = 8'b00000000;

        // Character: o (ASCII 111)
        font_memory[111][0] = 8'b00000000;
        font_memory[111][1] = 8'b00000000;
        font_memory[111][2] = 8'b00011100;
        font_memory[111][3] = 8'b00100010;
        font_memory[111][4] = 8'b01000010;
        font_memory[111][5] = 8'b01000100;
        font_memory[111][6] = 8'b00111000;
        font_memory[111][7] = 8'b00000000;

        // Character: p (ASCII 112)
        font_memory[112][0] = 8'b00000000;
        font_memory[112][1] = 8'b00000000;
        font_memory[112][2] = 8'b01011100;
        font_memory[112][3] = 8'b01100010;
        font_memory[112][4] = 8'b01000010;
        font_memory[112][5] = 8'b01111100;
        font_memory[112][6] = 8'b01000000;
        font_memory[112][7] = 8'b01000000;

        // Character: q (ASCII 113)
        font_memory[113][0] = 8'b00000000;
        font_memory[113][1] = 8'b00000000;
        font_memory[113][2] = 8'b00111110;
        font_memory[113][3] = 8'b01000010;
        font_memory[113][4] = 8'b01000110;
        font_memory[113][5] = 8'b00111010;
        font_memory[113][6] = 8'b00000010;
        font_memory[113][7] = 8'b00000010;

        // Character: r (ASCII 114)
        font_memory[114][0] = 8'b00000000;
        font_memory[114][1] = 8'b00000000;
        font_memory[114][2] = 8'b00101100;
        font_memory[114][3] = 8'b00110000;
        font_memory[114][4] = 8'b00100000;
        font_memory[114][5] = 8'b00100000;
        font_memory[114][6] = 8'b00100000;
        font_memory[114][7] = 8'b00000000;

        // Character: s (ASCII 115)
        font_memory[115][0] = 8'b00000000;
        font_memory[115][1] = 8'b00000000;
        font_memory[115][2] = 8'b00111100;
        font_memory[115][3] = 8'b01000000;
        font_memory[115][4] = 8'b00111100;
        font_memory[115][5] = 8'b00000010;
        font_memory[115][6] = 8'b01111100;
        font_memory[115][7] = 8'b00000000;

        // Character: t (ASCII 116)
        font_memory[116][0] = 8'b00010000;
        font_memory[116][1] = 8'b00010000;
        font_memory[116][2] = 8'b00111100;
        font_memory[116][3] = 8'b00010000;
        font_memory[116][4] = 8'b00010000;
        font_memory[116][5] = 8'b00010000;
        font_memory[116][6] = 8'b00001100;
        font_memory[116][7] = 8'b00000000;

        // Character: u (ASCII 117)
        font_memory[117][0] = 8'b00000000;
        font_memory[117][1] = 8'b00000000;
        font_memory[117][2] = 8'b01000010;
        font_memory[117][3] = 8'b01000010;
        font_memory[117][4] = 8'b01000010;
        font_memory[117][5] = 8'b01000110;
        font_memory[117][6] = 8'b00111010;
        font_memory[117][7] = 8'b00000000;

        // Character: v (ASCII 118)
        font_memory[118][0] = 8'b00000000;
        font_memory[118][1] = 8'b00000000;
        font_memory[118][2] = 8'b01000010;
        font_memory[118][3] = 8'b01000010;
        font_memory[118][4] = 8'b00100100;
        font_memory[118][5] = 8'b00100100;
        font_memory[118][6] = 8'b00011000;
        font_memory[118][7] = 8'b00000000;

        // Character: w (ASCII 119)
        font_memory[119][0] = 8'b00000000;
        font_memory[119][1] = 8'b00000000;
        font_memory[119][2] = 8'b10010010;
        font_memory[119][3] = 8'b10010010;
        font_memory[119][4] = 8'b01010100;
        font_memory[119][5] = 8'b01101100;
        font_memory[119][6] = 8'b00101000;
        font_memory[119][7] = 8'b00000000;

        // Character: x (ASCII 120)
        font_memory[120][0] = 8'b00000000;
        font_memory[120][1] = 8'b00000000;
        font_memory[120][2] = 8'b01100010;
        font_memory[120][3] = 8'b00010100;
        font_memory[120][4] = 8'b00011000;
        font_memory[120][5] = 8'b00101000;
        font_memory[120][6] = 8'b01000110;
        font_memory[120][7] = 8'b00000000;

        // Character: y (ASCII 121)
        font_memory[121][0] = 8'b00000000;
        font_memory[121][1] = 8'b00000000;
        font_memory[121][2] = 8'b01000010;
        font_memory[121][3] = 8'b00100100;
        font_memory[121][4] = 8'b00100100;
        font_memory[121][5] = 8'b00011000;
        font_memory[121][6] = 8'b00010000;
        font_memory[121][7] = 8'b01100000;

        // Character: z (ASCII 122)
        font_memory[122][0] = 8'b00000000;
        font_memory[122][1] = 8'b00000000;
        font_memory[122][2] = 8'b01111110;
        font_memory[122][3] = 8'b00000100;
        font_memory[122][4] = 8'b00011000;
        font_memory[122][5] = 8'b00100000;
        font_memory[122][6] = 8'b01111110;
        font_memory[122][7] = 8'b00000000;

        // Character: { (ASCII 123)
        font_memory[123][0] = 8'b00001100;
        font_memory[123][1] = 8'b00010000;
        font_memory[123][2] = 8'b00010000;
        font_memory[123][3] = 8'b00110000;
        font_memory[123][4] = 8'b00110000;
        font_memory[123][5] = 8'b00010000;
        font_memory[123][6] = 8'b00010000;
        font_memory[123][7] = 8'b00001100;

        // Character: | (ASCII 124)
        font_memory[124][0] = 8'b00010000;
        font_memory[124][1] = 8'b00010000;
        font_memory[124][2] = 8'b00010000;
        font_memory[124][3] = 8'b00010000;
        font_memory[124][4] = 8'b00010000;
        font_memory[124][5] = 8'b00010000;
        font_memory[124][6] = 8'b00010000;
        font_memory[124][7] = 8'b00010000;

        // Character: } (ASCII 125)
        font_memory[125][0] = 8'b00110000;
        font_memory[125][1] = 8'b00001000;
        font_memory[125][2] = 8'b00001000;
        font_memory[125][3] = 8'b00001100;
        font_memory[125][4] = 8'b00001100;
        font_memory[125][5] = 8'b00001000;
        font_memory[125][6] = 8'b00001000;
        font_memory[125][7] = 8'b00110000;

        // Character: ~ (ASCII 126)
        font_memory[126][0] = 8'b00000000;
        font_memory[126][1] = 8'b00000000;
        font_memory[126][2] = 8'b01100000;
        font_memory[126][3] = 8'b10010010;
        font_memory[126][4] = 8'b00001100;
        font_memory[126][5] = 8'b00000000;
        font_memory[126][6] = 8'b00000000;
        font_memory[126][7] = 8'b00000000;

        // Character:  (ASCII 127)
        font_memory[127][0] = 8'b11111110;
        font_memory[127][1] = 8'b10000010;
        font_memory[127][2] = 8'b11001110;
        font_memory[127][3] = 8'b10110010;
        font_memory[127][4] = 8'b10010010;
        font_memory[127][5] = 8'b11101010;
        font_memory[127][6] = 8'b10000110;
        font_memory[127][7] = 8'b11111110;

    end

    always @(*) begin
        pixels = font_memory[char_code][row];
    end

endmodule
